org: plantix09
app: aws-node-project
service: crm-service

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    SECRET_NAME: AppBeta
    DB_NAME: task3
    db_username: ${ssm:/project/aws-node/db_username}
    db_password: ${ssm:/project/aws-node/db_password}
    db_engine: ${ssm:/project/aws-node/db_engine}
    db_host: ${ssm:/project/aws-node/db_host}
    db_port: ${ssm:/project/aws-node/db_port}
    db_dbInstanceIdentifier: ${ssm:/project/aws-node/db_dbInstanceIdentifier}
  vpc:
    securityGroupIds:
      - sg-0f17942f8994fc08e
    subnetIds:
      - subnet-e646be9d

functions:
  createCustomer:
    handler: createCustomer.handler
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-0f17942f8994fc08e
      subnetIds:
        - subnet-e646be9d
    events:
      - http:
          path: customers
          method: post

  getCustomers:
    handler: getCustomers.handler
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-0f17942f8994fc08e
      subnetIds:
        - subnet-e646be9d
    events:
      - http:
          path: customers
          method: get

  updateCustomer:
    handler: updateCustomer.handler
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-0f17942f8994fc08e
      subnetIds:
        - subnet-e646be9d
    events:
      - http:
          path: customers/{customer_id}
          method: put

resources:
  Resources:
    LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service: "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: "LambdaExecutionPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "secretsmanager:GetSecretValue"
                    - "secretsmanager:PutSecretValue"
                    - "rds:Connect"
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "*"

package:
  include:
    - createCustomer.js
    - getCustomers.js
    - updateCustomer.js
